services:
  bcfk:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3001
    volumes:
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
    driver: local